global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-broker'
    scrape_timeout: 10s
    static_configs:
      - targets:
          - 'jmx-exporter-0:7071'
          - 'jmx-exporter-1:7071'
          - 'jmx-exporter-2:7071'
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        regex: 'jmx-exporter-(\d+):(.+)'
        target_label: instance
        replacement: 'kafka-$1'

      - source_labels: [__address__]
        regex: 'jmx-exporter-(\d+):(.+)'
        target_label: hostname
        replacement: 'kafka-$1'

      - source_labels: [__address__]
        regex: 'jmx-exporter-(\d+):(.+)'
        target_label: __address__
        replacement: 'jmx-exporter-$1:$2'
