apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        image: danielqsj/kafka-exporter:latest  # 官方 Kafka Exporter 映像
        ports:
        - containerPort: 9308
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter-service
  namespace: monitoring
spec:
  selector:
    app: kafka-exporter
  ports:
    - protocol: TCP
      port: 9308
      targetPort: 9308
