{
 "title": "KRaft",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } }
  ]
 },
 "panels": [
  { "title": "KRaft Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_server_raft_metrics_high_watermark{env=\"$env\", job=\"kafka-broker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Brokers Count",
   "type": "stat",
   "description": "When using KRaft, the number of registered and unfenced brokers as observed by this controller.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activebrokercount{env=\"$env\", job=\"kafka-broker\"})/count(kafka_controller_kafkacontroller_activebrokercount{env=\"$env\", job=\"kafka-broker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fenced Broker Count",
   "type": "stat",
   "description": "When using KRaft, the number of registered but fenced brokers as observed by this controller.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_fencedbrokercount{env=\"$env\", job=\"kafka-broker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Leader",
   "type": "stat",
   "description": "The current quorum leader’s id; -1 indicates unknown.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_raft_metrics_current_leader{env=\"$env\", job=\"kafka-broker\"})/count(kafka_server_raft_metrics_current_leader{env=\"$env\", job=\"kafka-broker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "The current quorum epoch.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_server_raft_metrics_current_epoch{env=\"$env\", job=\"kafka-broker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Error Count",
   "type": "stat",
   "description": "The number of times this controller node has encountered an error during metadata log processing.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_metadataerrorcount{env=\"$env\", job=\"kafka-broker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Record lag ms",
   "type": "timeseries",
   "description": "The difference between now and the timestamp of the last record from the cluster metadata partition that was applied by the controller. For active controllers the value of this lag is always zero.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_lastappliedrecordlagms{env=\"$env\", job=\"kafka-broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Append Records Rate",
   "type": "timeseries",
   "description": "The average number of records appended per sec by the leader of the raft quorum.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_append_records_rate{env=\"$env\", job=\"kafka-broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fetch Record Rate",
   "type": "timeseries",
   "description": "The average number of records fetched from the leader of the raft quorum.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_fetch_records_rate{env=\"$env\", job=\"kafka-broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Maximum time spent on electing a new leader",
   "type": "timeseries",
   "description": "The maximum time in milliseconds spent on electing a new leader.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_election_latency_max{env=\"$env\", job=\"kafka-broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average time spent to commit an entry in the raft log",
   "type": "timeseries",
   "description": "The average time in milliseconds to commit an entry in the raft log.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_commit_latency_avg{env=\"$env\", job=\"kafka-broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Maximum time spent to commit an entry in the raft log",
   "type": "timeseries",
   "description": "The max time in milliseconds to commit an entry in the raft log.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_commit_latency_max{env=\"$env\", job=\"kafka-broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Brokers Count",
   "type": "timeseries",
   "description": "When using KRaft, the number of registered and unfenced brokers as observed by this controller.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activebrokercount{env=\"$env\", job=\"kafka-broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}